//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TRANSPORTEEntities : DbContext
    {
        public TRANSPORTEEntities()
            : base("name=TRANSPORTEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ABONOCXP> ABONOCXP { get; set; }
        public virtual DbSet<CAMION> CAMION { get; set; }
        public virtual DbSet<CATEGORIA> CATEGORIA { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<COMPRA> COMPRA { get; set; }
        public virtual DbSet<COMPRADETA> COMPRADETA { get; set; }
        public virtual DbSet<CUENTAXPAGAR> CUENTAXPAGAR { get; set; }
        public virtual DbSet<FORMAPAGO> FORMAPAGO { get; set; }
        public virtual DbSet<INSUMO> INSUMO { get; set; }
        public virtual DbSet<PAGOAPILOTO> PAGOAPILOTO { get; set; }
        public virtual DbSet<PILOTO> PILOTO { get; set; }
        public virtual DbSet<PRELIQUIDACION> PRELIQUIDACION { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<SALIDAINSUMO> SALIDAINSUMO { get; set; }
        public virtual DbSet<SALIDAINSUMODETA> SALIDAINSUMODETA { get; set; }
        public virtual DbSet<SERVICIO> SERVICIO { get; set; }
        public virtual DbSet<TIPOUSUARIO> TIPOUSUARIO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<VALECOMBUSTIBLE> VALECOMBUSTIBLE { get; set; }
        public virtual DbSet<VIAJE> VIAJE { get; set; }
        public virtual DbSet<COMPRA2> COMPRA2 { get; set; }
        public virtual DbSet<VENTA> VENTA { get; set; }
    }
}
