//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRADETA
    {
        public int NODETALLE { get; set; }
        public long IDCOMPRA { get; set; }
        public Nullable<int> IDINSUMO { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
    
        public virtual COMPRA COMPRA { get; set; }
        public virtual INSUMO INSUMO { get; set; }
    }
}
