//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPRA()
        {
            this.COMPRADETA = new HashSet<COMPRADETA>();
            this.CUENTAXPAGAR = new HashSet<CUENTAXPAGAR>();
        }
    
        public long NOCOMPRA { get; set; }
        public Nullable<int> PROVEEDOR { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal TOTAL { get; set; }
        public Nullable<short> FORMAPAGO { get; set; }
        public Nullable<System.DateTime> FECHAPAGO { get; set; }
        public string NOFACTURA { get; set; }
    
        public virtual FORMAPAGO FORMAPAGO1 { get; set; }
        public virtual PROVEEDOR PROVEEDOR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRADETA> COMPRADETA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUENTAXPAGAR> CUENTAXPAGAR { get; set; }
    }
}
