//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGOAPILOTO
    {
        public long IDPAGO { get; set; }
        public System.DateTime FECHAREGISTRO { get; set; }
        public string NODOCUMENTO { get; set; }
        public string DOCUMENTO { get; set; }
        public Nullable<decimal> QUINCENA { get; set; }
        public Nullable<decimal> VIATICOS { get; set; }
        public Nullable<decimal> ENTRADAS { get; set; }
        public Nullable<decimal> PARQUEO { get; set; }
        public Nullable<decimal> DESCARGA { get; set; }
        public Nullable<decimal> OTROS { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string PLACA { get; set; }
        public string PILOTO { get; set; }
    }
}
