//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALIDAINSUMO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SALIDAINSUMO()
        {
            this.SALIDAINSUMODETA = new HashSet<SALIDAINSUMODETA>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> SERVICIO { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
    
        public virtual SERVICIO SERVICIO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALIDAINSUMODETA> SALIDAINSUMODETA { get; set; }
    }
}
