//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICIO()
        {
            this.SALIDAINSUMO = new HashSet<SALIDAINSUMO>();
        }
    
        public int IDSERVICIO { get; set; }
        public Nullable<int> CAMION { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<decimal> COSTO { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
    
        public virtual CAMION CAMION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALIDAINSUMO> SALIDAINSUMO { get; set; }
    }
}
