//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIAJE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VIAJE()
        {
            this.VALECOMBUSTIBLE = new HashSet<VALECOMBUSTIBLE>();
        }
    
        public long CORRELATIVO { get; set; }
        public string NOVIAJE { get; set; }
        public string FOLIO { get; set; }
        public System.DateTime FECHAREGISTRO { get; set; }
        public string DESTINO { get; set; }
        public string ORIGEN { get; set; }
        public Nullable<int> PILOTO { get; set; }
        public Nullable<int> CAMION { get; set; }
        public Nullable<System.DateTime> FECHAENTREGA { get; set; }
        public Nullable<decimal> PAGOPILOTO { get; set; }
        public Nullable<decimal> CANTDIESEL { get; set; }
        public Nullable<decimal> PRECIOVIAJE { get; set; }
        public Nullable<bool> REGISTRADO { get; set; }
        public Nullable<bool> DESPACHADO { get; set; }
        public Nullable<bool> PAGADO { get; set; }
        public Nullable<bool> FACTURADO { get; set; }
        public Nullable<int> USUARIO { get; set; }
        public Nullable<bool> ESTADO { get; set; }
        public Nullable<decimal> TNMOVIDAS { get; set; }
        public Nullable<int> KILOMETRAJE { get; set; }
        public Nullable<long> PRELIQUIDACION { get; set; }
        public Nullable<long> NOPAGO { get; set; }
        public string CLIENTE { get; set; }
    
        public virtual CAMION CAMION1 { get; set; }
        public virtual PILOTO PILOTO1 { get; set; }
        public virtual PRELIQUIDACION PRELIQUIDACION1 { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VALECOMBUSTIBLE> VALECOMBUSTIBLE { get; set; }
    }
}
